/* eslint-disable react/no-unescaped-entities */
/* eslint-disable @next/next/no-img-element */
/* eslint-disable react/jsx-no-comment-textnodes */
import type { NextPage } from "next";
import Head from "next/head";
import { Col, Row, Button, Card, Space, Typography, Badge } from "antd";
import {
  DownloadOutlined,
  EyeInvisibleOutlined,
  DeleteOutlined,
  PlusOutlined,
  ShareAltOutlined,
  MessageOutlined,
  MinusOutlined,
} from "@ant-design/icons";
import CustomProgress from "./component/slider";
import Listes from "./component/list";
import Navigation from "./component/navigation";
import WorkForce from "./component/workforce";
import Proposal from "./component/proposal";
const Home: NextPage = () => {
  const { Text } = Typography;
  return (
    <div>
      <Head>
        <title>Workspace Proposal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <br />
      <br />
      <WorkForce text={"WeWork + Salesforce"} buttonText={"Publish/Share"} />
      <br />
      <div className="div1">
        <Proposal />
      </div>
      {/* https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV4FheZ2Vug9em0KjgqPwgWA178OBdVGA22UnrvSBXkWadwy8eirYVIaviyC5WA_w2rP-y5yOkbSQ&usqp=CAU&ec=48665698 */}
      <Card bordered={true} className="wework">
        <div className="salesforce">
          <img
            alt="example"
            src="https://www.logo.wine/a/logo/WeWork/WeWork-Icon-Logo.wine.svg"
            className="imagewe"
          />
          <PlusOutlined />
          <img
            alt="example"
            src="https://www.salesforce.com/news/wp-content/uploads/sites/3/2021/05/Salesforce-logo.jpg?resize=1024,576"
            className="imagesalesforce"
          />
        </div>
      </Card>
      <Row>
        <Col span={8} className="colStyle6">
          Project Scope Recap
        </Col>
        <Col span={8} offset={8} className="colStyle7">
          <div style={{ position: "relative", left: " -10rem" }}>
            Mutual Action Plan
          </div>
          <div>
            <CustomProgress percent={3} steps={17} />
          </div>
        </Col>
      </Row>
      <br />
      <Row style={{ boxShadow: "0px 1px 0px 0px gainsboro" }}>
        <Col span={9} className="colStyle8">
          {" "}
          <Button className="buttonfirst">Basic Info</Button>{" "}
          <Button className="buttonsize">Files</Button>{" "}
          <Button className="buttonsize">Mutual Action Plan</Button>{" "}
          <Button className="buttonsize">Contact</Button>{" "}
        </Col>
        <Col span={7} offset={8} className="colStyle9">
          <Button className="buttonsize">Internal Actions</Button>
        </Col>
      </Row>
      <br />
      <br />

      <Row>
        <Col span={18} push={6}>
          <Space direction="vertical" size={16}>
            <Card
              title="Company Profile"
              extra={
                <div className="companyprofile">
                  <DownloadOutlined className="iconssizesnew" />
                  <EyeInvisibleOutlined className="iconssizesnew" />
                  <DeleteOutlined className="iconssizesnew" />
                </div>
              }
              className="companyworks"
              cover={
                <div className="companytask">
                  <img
                    alt="example"
                    src="https://ctfassets.imgix.net/vh7r69kgcki3/7FftQJ8Wcw7y0TQ8NLIS3b/157b910fa71a001dc85347eb639c626b/Web_150DPI-WeWork__-__21_Collyer_Quay__-__Singapore-15.jpg?auto=format%20compress&fit=crop&q=50&w=500px"
                    className="workimage"
                  />
                  <div className="nameofcompany">
                    <Text className="text1">wework</Text>
                    <br />
                    <Text className="text2">
                      For all the ways you work, we're here
                    </Text>
                  </div>
                </div>
              }
            ></Card>
          </Space>
          <div className="iconmsgshare">
            <Badge count={6} offset={[5, -2]}>
              <MessageOutlined className="iconsizelast" />
            </Badge>
            <MinusOutlined className="minusicon" />
            <ShareAltOutlined className="iconsizelast" />
          </div>
        </Col>
        <Col span={6} pull={18}>
          <Listes />
        </Col>
      </Row>
      <br />
      <br />
    </div>
  );
};

export default Home;
